# Since we build and test in Docker we dont
# need node at build time
language: c

services:
  - docker

script:
  - make travis
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then make clean && make publish && make deploy; fi
